# Generated by Django 4.2.8 on 2026-06-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_anomalylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulated_time', models.DateTimeField(blank=True, null=True, verbose_name='Симулированное время')),
            ],
            options={
                'verbose_name': 'Переопределение времени',
                'verbose_name_plural': 'Переопределение времени',
            },
        ),
        migrations.RemoveField(
            model_name='anomalyalert',
            name='ml_score',
        ),
        migrations.AlterField(
            model_name='anomalyalert',
            name='anomaly_type',
            field=models.CharField(choices=[('overload', 'Перегрузка'), ('forgotten', 'Забытое устройство'), ('night_work', 'Ночная работа'), ('high_baseline', 'Высокий фон'), ('spike', 'Резкий скачок')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='anomaly_type',
            field=models.CharField(choices=[('overload', 'Перегрузка'), ('night_work', 'Ночная работа'), ('forgotten', 'Забытое устройство')], max_length=50, verbose_name='Тип'),
        ),
    ]
