# Generated by Django 4.2.8 on 2026-06-03 22:25

from django.db import migrations, models
from django.db.models import Count


def deduplicate_anomaly_alerts(apps, schema_editor):
    AnomalyAlert = apps.get_model('energy', 'AnomalyAlert')
    db_alias = schema_editor.connection.alias

    dupes = (
        AnomalyAlert.objects.using(db_alias)
        .filter(resolved_at__isnull=True)
        .values('device_id', 'anomaly_type')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    for group in dupes:
        ids = (
            AnomalyAlert.objects.using(db_alias)
            .filter(
                device_id=group['device_id'],
                anomaly_type=group['anomaly_type'],
                resolved_at__isnull=True,
            )
            .order_by('-detected_at')
            .values_list('id', flat=True)
        )
        keep_id = ids[0]
        delete_ids = list(ids[1:])
        AnomalyAlert.objects.using(db_alias).filter(id__in=delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_timeoverride_remove_anomalyalert_ml_score_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicate_anomaly_alerts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='anomalyalert',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('device', 'anomaly_type'), name='uq_anomaly_device_type_unresolved'),
        ),
    ]
